spring:
  profiles:
    active: prod


---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/carecompare
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  profiles: prod
  datasource:
    url: us-cdbr-iron-east-02.cleardb.net/heroku_7eae045b6b3c712?reconnect=true
    username: b1376580e3d75d
    password: 538573bb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update